import { supabase } from './supabase'
import React,{useEffect,useMemo,useState} from 'react';import{createRoot}from'react-dom/client';import{createClient}from'@supabase/supabase-js';import'./style.css';
const sb=createClient(import.meta.env.VITE_SUPABASE_URL||'',import.meta.env.VITE_SUPABASE_ANON_KEY||'');const pid=(()=>{let x=localStorage.getItem('dama_pid');if(!x){x=crypto.randomUUID();localStorage.setItem('dama_pid',x)}return x})();
const dirs=[[1,1],[1,-1],[-1,1],[-1,-1]], inside=(r,c)=>r>=0&&r<8&&c>=0&&c<8;const initial=()=>Array.from({length:8},(_,r)=>Array.from({length:8},(_,c)=>(r+c)%2?(r<3?'b':r>4?'r':null):null));
function moves(b,p){let cap=[],normal=[];for(let r=0;r<8;r++)for(let c=0;c<8;c++){let x=b[r][c];if(!x||x.toLowerCase()!=p)continue;let k=x===x.toUpperCase();if(k)for(let[d,e]of dirs){let R=r+d,C=c+e,seen=false,en=null;while(inside(R,C)){let q=b[R][C];if(!q){(seen?cap:normal).push({from:[r,c],to:[R,C],capture:en})}else{if(q.toLowerCase()==p||seen)break;seen=true;en=[R,C]}R+=d;C+=e}}else{let d=p==='r'?-1:1;for(let e of[-1,1]){let R=r+d,C=c+e;if(inside(R,C)&&!b[R][C])normal.push({from:[r,c],to:[R,C]});let R2=r+2*d,C2=c+2*e;if(inside(R2,C2)&&b[R][C]&&b[R][C].toLowerCase()!=p&&!b[R2][C2])cap.push({from:[r,c],to:[R2,C2],capture:[R,C]})}}}return cap.length?cap:normal}
function apply(b,m){let n=b.map(x=>x.slice()),p=n[m.from[0]][m.from[1]];n[m.from[0]][m.from[1]]=null;if(m.capture)n[m.capture[0]][m.capture[1]]=null;let[r,c]=m.to;if(p==='r'&&r===0)p='R';if(p==='b'&&r===7)p='B';n[r][c]=p;return n}
function App(){let[name,setName]=useState(localStorage.getItem('dama_name')||''),[code,setCode]=useState(''),[mode,setMode]=useState('home'),[g,setG]=useState(null),[b,setB]=useState(initial()),[turn,setTurn]=useState('r'),[sel,setSel]=useState(null),[err,setErr]=useState('');let mine=g?(g.red_player_id===pid?'r':g.black_player_id===pid?'b':null):null,ms=useMemo(()=>moves(b,turn),[b,turn]);
useEffect(()=>{if(!g)return;let ch=sb.channel('g'+g.id).on('postgres_changes',{event:'UPDATE',schema:'public',table:'games',filter:`id=eq.${g.id}`},p=>{setG(p.new);setB(p.new.board_state);setTurn(p.new.current_turn)}).subscribe();return()=>sb.removeChannel(ch)},[g?.id]);
async function create(){if(!name.trim())return setErr('اكتب اسمك');localStorage.setItem('dama_name',name);let room=Math.random().toString(36).slice(2,7).toUpperCase(),{data,error}=await sb.from('games').insert({room_code:room,red_player_id:pid,red_name:name,board_state:initial(),current_turn:'r',status:'waiting'}).select().single();if(error)return setErr(error.message);setG(data);setB(data.board_state);setTurn('r');setMode('game')}
async function join(){if(!name.trim())return setErr('اكتب اسمك');let{data,error}=await sb.from('games').select('*').eq('room_code',code.trim().toUpperCase()).eq('status','waiting').single();if(error)return setErr('الكود غير صحيح');let q=await sb.from('games').update({black_player_id:pid,black_name:name,status:'playing'}).eq('id',data.id).select().single();if(q.error)return setErr(q.error.message);setG(q.data);setB(q.data.board_state);setTurn(q.data.current_turn);setMode('game')}
async function click(r,c){if(!g||g.status!=='playing'||turn!==mine)return;if(b[r][c]?.toLowerCase()===mine)return setSel([r,c]);if(!sel)return;let m=ms.find(x=>x.from[0]===sel[0]&&x.from[1]===sel[1]&&x.to[0]===r&&x.to[1]===c);if(!m)return;let nb=apply(b,m),nx=turn==='r'?'b':'r',opp=nx,win=!nb.flat().some(x=>x?.toLowerCase()===opp)||!moves(nb,opp).length?turn:null;let u=await sb.from('games').update({board_state:nb,current_turn:nx,status:win?'finished':'playing',winner_id:win?(win==='r'?g.red_player_id:g.black_player_id):null,result:win?(win==='r'?'red_win':'black_win'):null,ended_at:win?new Date().toISOString():null}).eq('id',g.id).select().single();if(u.error)setErr(u.error.message);setSel(null)}
return <><header><b>داما</b></header>{mode==='home'&&<main><h1>داما</h1><input placeholder="اسمك" value={name} onChange={e=>setName(e.target.value)}/><button onClick={create}>إنشاء مباراة</button><button onClick={()=>setMode('join')}>انضمام</button>{err&&<p>{err}</p>}</main>}{mode==='join'&&<main><h2>انضمام</h2><input placeholder="كود الغرفة" value={code} onChange={e=>setCode(e.target.value)}/><button onClick={join}>انضمام</button><button onClick={()=>setMode('home')}>رجوع</button>{err&&<p>{err}</p>}</main>}{mode==='game'&&g&&<main><h2>{g.red_name} 🔴 × ⚫ {g.black_name||'بانتظار خويك'}</h2><p>الكود: <b>{g.room_code}</b></p><p>{g.status==='waiting'?'أرسل الكود لخويك وانتظر':g.status==='finished'?'انتهت المباراة':turn===mine?'دورك':'دور خويك'}</p><div className="board">{b.map((row,r)=>row.map((x,c)=><button className={(r+c)%2?'dark':'light'} onClick={()=>click(r,c)}>{x&&<span className={'piece '+(x.toLowerCase()==='r'?'red':'black')}>{x===x.toUpperCase()?'♛':''}</span>}</button>))}</div>{err&&<p>{err}</p>}</main>}</>};createRoot(document.getElementById('root')).render(<App/>);
